pastebin/urls.py
from django.urls import path

from . import views, user_module

app_name = 'pastebin'
urlpatterns = [
    path('', views.NewPostView.as_view(), name='NewPost'),
    path('savePost/', views.savePost, name='SavenewPost'),
    path('<int:post_id>/savePost/', views.savePost, name='SavePost'),
    path('<str:url>/displayPost/', views.displayPost, name='DisplayPost'),
    path('newUserRegistration/', views.NewUserView, name='NewUserView'),
    path('<int:user_id>/viewallpost/', views.DisplayAllPostView.as_view(), name='DisplayAllPost'),
    path('saveUser/', user_module.saveNewUser, name='saveNewUser'),
    path('login/', user_module.authenticateUser, name='LoginUser'),
    path('logout/', user_module.logOutUser, name='LogOutView'),
]

pastebin_url/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('pastebin/', include('pastebin.urls')),
    path('admin/', admin.site.urls),
]

pastebin/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.
class POST(models.Model):
    post_info = models.TextField(max_length=2000)
    file_path = models.CharField(max_length=500)
    entry_date = models.DateTimeField('post entry date')
    last_updated = models.BooleanField(default=False)
    post_update = models.DateTimeField(auto_now_add=True)
    is_deleted = models.BooleanField(default=False)
    is_published = models.BooleanField(default=True)
    title = models.CharField(default = 'Untitled', max_length=30)
    user = models.ForeignKey(User, default=1, on_delete=models.CASCADE)

    def __str__(self): 
        return self.post_info


class URL(models.Model):
    post = models.ForeignKey(POST, on_delete=models.CASCADE)
    length = models.IntegerField(default=0)
    short_url = models.CharField(max_length=15)
    last_updated = models.BooleanField(default=False)
    url_update = models.DateTimeField(auto_now_add=True)
    is_deleted = models.BooleanField(default=False)
    is_published = models.BooleanField(default=True)
    def __str__(self): 
        return self.short_url

pastebin/forms.py
from django import forms

class PostForm(forms.Form):
    post = forms.CharField(widget=forms.Textarea)

    def send_data(self):

        pass

pastebin/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.views import generic
from .models import POST, URL
from django.urls import reverse
from django.shortcuts import get_object_or_404, render
from django.utils import timezone
import short_url, os
from django.contrib.messages import get_messages
from django.db import transaction
from pathlib import Path

MYPATH = Path().absolute()

FILEPATH = str(MYPATH) + '/pastebin/pastebin_files/'
# Create your views here.

class NewPostView(generic.ListView):
    model = POST
    template_name = 'pastebin/newpostview.html'

class DisplayAllPostView(generic.ListView):
    template_name = 'pastebin/listallposts.html'
    context_object_name = 'list_object'
    model = POST
    def get_queryset(self):
        current_user_id = self.request.session.get('user_id', 0)
        if current_user_id > 0:
            return POST.objects.raw('SELECT post.id, post.file_path, post.title, post.user_id, url.id AS url_id, url.short_url  FROM pastebin_post AS post INNER JOIN pastebin_url AS url ON post.id = url.post_id WHERE user_id = %s ', [current_user_id])
            

@transaction.atomic
def savePost(request, post_id=0):
    sid = transaction.savepoint()
    if post_id==0:
        try:
            newpost = POST(post_info = request.POST['post_info'], entry_date = timezone.now())
            current_user_id = request.session.get('user_id', 0)
            if current_user_id > 0:
                newpost.user_id = current_user_id

            newpost.save()
            new_url = short_url.encode_url(newpost.id)
            file_path = newFile(current_user_id, new_url, newpost.post_info)
            POST.objects.filter(id = newpost.id).update(file_path = file_path)
            selected_url = newpost.url_set.create(short_url=new_url)
            
        except Exception as e:
            transaction.savepoint_rollback(sid)
            return render(request, 'pastebin/newpostview.html', {
                'error_message': 'Error in saving this entry, Error Info:' + str(e),
                })
        transaction.savepoint_commit(sid)
        return HttpResponseRedirect(reverse('pastebin:DisplayPost', args=(new_url,)))
    else:
        try:
            old_post = get_object_or_404(POST, pk=post_id)
            old_post.post_info = request.POST['post_info']
            old_post.last_updated = True
            old_post.post_update = timezone.now()
            update_file = updateFile(old_post.file_path, request.POST['post_info'])
            old_post.save()
            
        except (KeyError, POST.DoesNotExist):
            transaction.savepoint_rollback(sid)
            return render(request, 'pastebin/newpostview.html', {
                'post_object': old_post,
                'error_message': "Error in fetchin/updating post",
            })
        old_url = short_url.encode_url(old_post.id)
        transaction.savepoint_commit(sid)
        return HttpResponseRedirect(reverse('pastebin:DisplayPost', args=(old_url,))) 

def displayPost(request, url):
    post_id = short_url.decode_url(url)
    try:
        p = get_object_or_404(POST, id = post_id)
        p.info_from_file = readFile(p.file_path)
    except (KeyError, POST.DoesNotExist):
        return render(request, 'pastebin/newpostview.html', {
            'error_message': "Error in fetchin/updating post",
        })

    return render(request, 'pastebin/newpostview.html', {
            'post_object' : p
            })

#new User Registration View
def NewUserView(request):
    return render(request, 'pastebin/newUser.html', )

#function to make a new file
#write the textarea into a .txt file
#takes the converted shortened url as a filename and the textarea text as the input
def newFile(user_id, filename, text):
    if user_id > 0:
        if not os.path.isdir(FILEPATH + str(user_id)):
            os.makedirs(FILEPATH + str(user_id))
        full_filename = FILEPATH + str(user_id) + '/' + filename + '.txt'
    else:
        full_filename = FILEPATH + str(filename) + '.txt' 

    if text is not None:
        try:
            f = open(full_filename, 'w+')
            f.write(text)
            f.close()
        except Exception as e:
            raise Exception(str(e))

    return full_filename

#function to update the file content
def updateFile(fullpath, text):

    if text is not None:
        try:
            f = open(fullpath, 'w+')
            f.write(text)
            f.close()
        except Exception as e:
            raise Exception(str(e))

    return fullpath

#function to read file and return the post/text
def readFile(fullpath):
    f = open(fullpath, 'r')
    post = f.read()
    f.close()

    return post

pastebin/templates/pastebin/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'parsley.css' %}">
    <link rel="stylesheet" href="{% static 'pastebin/bootstrap.css' %}" crossorigin="anonymous">
    <script src="{% static 'jquery.js' %}"></script>
    <script src="{% static 'parsley.js' %}"></script>
    <title>Django PASTEBIN</title>
  </head>
  <body>
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-12">
          <h1 class="mt-2">DJANGO PASTEBIN APP</h1>
          <hr class="mt-0 mb-4">
            {% if messages %}
            <ul>
               {% for message in messages %}
              <li>
                 {% if message.level == 50 %}Important: {% endif %}
                    {{ message }}
                   {% endfor %}
              </li>
            </ul>
            {% endif %}
          </hr>
            <!-- {% if login_error_message %}<p><strong>{{ login_error_message }}</strong></p>{% endif %} -->
            {% if user.is_authenticated %}
            <!-- Uuser data:{{user}} --> </br>
                You are logged in as {% if user.first_name|length > 0 %} {{ user.first_name }} {{ user.last_name }} 
                {% else %} {{ user.username }} 
                {% endif %}
                <a class="btn btn-primary" href="{% url 'pastebin:LogOutView' %}" role="button">LOGOUT</a>
            {% else %}
            <!-- user data:{{user}} --> </br>
              <div class="row">
                <form action="{% url 'pastebin:LoginUser' %}" method="post" >
                  {% csrf_token %} 
                    Username: <input type="text" name="username" required minlength="4" maxlength="10"> 
                    PassWord: <input type="PassWord" name="password" required minlength="5">
                    <button class="btn btn-primary" type="submit">LOGIN</button>
                </form> &nbsp; &nbsp; &nbsp;
                <a class="btn btn-primary" href="{% url 'pastebin:NewUserView' %}" role="button">SIGNUP</a>
              </div>
            {% endif %}
          </br>
          {% block content %}
          {% endblock %}
        </div>
      </div>
    </div>
  </body>
</html>

pastebin/templates/pastebin/listallposts.html
{% extends 'pastebin/base.html' %}
{% load static %}

{% block content %}

    <div class="container">
        {% for post in list_object %}
            <div class="row">
                <a href="{% url 'pastebin:DisplayPost' post.short_url %}">{{post.title}}-----{{post.post_info}}</a>
            </div>
        {% endfor %}
    </div>
{% endblock %}

pastebin/templates/pastebin/login.html
{% load static %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

{%if user.is_authenticated %}
Uuser data:{{user}} </br>
    You are logged in as {% if user.first_name|length > 0 %} {{ user.first_name }} {{ user.last_name }} 
    {% else %} {{ user.username }} 
    {% endif %}

{% else %}
user data:{{user}} </br>
<form action="{% url 'pastebin:LoginUser' %}" method="post" data-parsley-validate>
{% csrf_token %} 
    Username: <input type="text" name="username" required minlength="5" maxlength="10"> 
    PassWord: <input type="text" name="password" required minlength="5">
    <button class="btn btn-primary" type="submit">LOGIN</button>
    <a class="btn btn-primary" href="{% url 'pastebin:NewUserView' %}" role="button">SIGNUP</a>
</form>

{% endif %}

pastebin/templates/pastebin/newUser.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'parsley.css' %}">
<link rel="stylesheet" href="{% static 'pastebin/bootstrap.css' %}" crossorigin="anonymous">
<script src="{% static 'jquery.js' %}"></script>
<script src="{% static 'parsley.js' %}"></script>

<div class="row justify-content-center">
    <h1 class="mt-2">DJANGO PASTEBIN APP</h1>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <div class="container">
        <div class="row justify-content-center">
            <form action="{% url 'pastebin:saveNewUser' %}" method="post" >
            {% csrf_token %}    
                </br></br>
                <div class="col">Username: <input type="text" name="username" required minlength="5" maxlength="10"></div>
                <div class="col">PassWord :<input type="password" name="password" required minlength="5"></div>
                <div class="col">First Name: <input type="text" name="firstname" required maxlength="10"></div>
                <div class="col">Last Name: <input type="text" name="lastname" required maxlength="10"></div>
                <div class="col">Email: <input type="text" name="email" data-parsley-type="email"></div>

                <div class="col"><button class="btn btn-primary" type="submit">Register</button></div>
            </form>
        </div>
    </div>
</div>

pastebin/templates/pastebin/newpostview.html
{% extends 'pastebin/base.html' %}
{% load static %}
{% block content %}

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <div class="container">
    <div class="row">
        {% if post_object.id > 0 and user.is_authenticated %}
            <div class = "col">
                <a class="btn btn-primary" href="{% url 'pastebin:DisplayAllPost' user.id %}" role="button">View Saved Posts</a>
            </div>
            <form action="{% url 'pastebin:SavePost' post_object.id %}" method="post">
            {% csrf_token %}
                <div class="col">
                    <textarea name="post_info" rows="10" cols="80">{{post_object.info_from_file}}</textarea>
                </div>
                <div class="col"><button class="btn btn-primary" type="submit">UPDATE post</button></div>
            </form>
        {% elif post_object.id > 0 %}
            <form action="{% url 'pastebin:SavenewPost' %}" method="post">
            {% csrf_token %}
                <div class="col">
                    <textarea name="post_info" rows="10" cols="80">{{post_object.info_from_file}}</textarea>
                </div>
            </form>
        {% elif user.is_authenticated %}
            <div class = "col">
                <a class="btn btn-primary" href="{% url 'pastebin:DisplayAllPost' user.id %}" role="button">View Saved Posts</a>
            </div>
            <form action="{% url 'pastebin:SavenewPost' %}" method="post">
            {% csrf_token %}
                <div class="col">
                    <textarea name="post_info" rows="10" cols="80" placeholder="Your pastebin text here..."></textarea>
                </div>
                <div class="col"><button class="btn btn-primary" type="submit">SAVE post</button></div>
            </form>
        {% else %}
            <form action="{% url 'pastebin:SavenewPost' %}" method="post">
            {% csrf_token %}
                <div class="col">
                    <textarea name="post_info" rows="10" cols="80" placeholder="Your pastebin text here..."></textarea>
                </div>
                <div class="col"><button class="btn btn-primary" type="submit">SAVE post</button></div>
            </form>
        {% endif %}
    </div>
    </div>
{% endblock %}